### ISSUE TITLE
Allow specifying custom reducer key

### ISSUE THREAD

**Issue by blackxored** [tdeekens/flopflip#110]
I'd like to have it under `features` in my state.

**Comment by blackxored** [comment]
The connected components default to the constant, so that makes it pretty much useless.

**Comment by tdeekens** [comment]
Not sure I follow. In my view you would connect in this way.

```js
import { selectFeatureToggle } from '@flopflip/react-redux';
import { connect } from 'react-redux';

const MySuperComponent = () => <div />;

const mapStateToProps = state => ({
   isExperimentalFeatureEnabled: selectFeatureToggle('myFeatureToggleName')(state)
})

export default  connect(mapStateToProps)(MySuperComponent);
```

That way `MySuperComponent` now has a prop of `isExperimentalFeatureEnabled`.

If you don't want to "connect" using the selectors you can use `injectFeatureToggle` like so:

```js
import { injectFeatureToggle } from '@flopflip/react-redux';

const MySuperComponent = () => <div />;

export default injectFeatureToggle('myFeatureToggleName', 'isExperimentalFeatureEnabled')(MySuperComponent);
```

Which results in the same.

**Comment by blackxored** [comment]
I mean in the sense of the additional complexity. I'd rather be able to use the components you provide (e.g `ToggleFeature`).

**Comment by tdeekens** [comment]
You can. Without any problems. You/we just as it as follows:

```js
import { ToggleFeature } from '@flopflip/react-redux';

const MySuperComponent = () => (
   <ToggleFeature flag="myFeatureToggleName">I might be here</ToggleFeature>
);
```

It connects to `redux` behind the scenes for you and you don't have to worry about it.

**Comment by blackxored** [comment]
But it doesn't work if your slice state it's on a different key, hence my point about customization.

**Comment by tdeekens** [comment]
Yes, but why do you want it on a different slices after all. I've not met a use case in which the components, helpers of the flopflip itself were not sufficient enough yielding one to mind about the slice itself.

**Comment by tdeekens** [comment]
I've verified once again that toggling within the `react-redux` package works. I've engaged with other library contributors to discuss if we feel this being viable for the library. We decided the flag constant to not be configurable and consider it being internal to the library. We are aware that this does not allow integrating the toggling components to an otherwise externally managed state slice. Outside of adapters and the libraries' internal reducers. We however don't feel we want to open up to that as a possibility. If toggles are managed externally we feel that toggling according to those should be fairly straight forward and out HoCs and components serve little benefit while we'd have to maintain the configuration option. We see this as an undesirable maintenance burden for the library to be configurable in regards to the state slice name.

I hope this is understandable and that I got you proposed feature correctly. Thanks for engaging with the library and we hope it might still serve a benefit eventually.

I will close this issue for that reason and due to inactivity.
