### ISSUE TITLE
A `cachePolicy` to guide behaviour of how cached flags are restored

### ISSUE THREAD

**Issue by tdeekens** [tdeekens/flopflip#1879]
A `cachaPolicy` similar to Apollo's `fetchPolicy` could help to steer behaviour of `flopflip` when flags are cachedf in local storage. 

To recap [this](https://www.apollographql.com/docs/react/data/queries/#supported-fetch-policies) is what Apollo defines as `fetchPolicies`.

![CleanShot 2024-03-23 at 22 26 27@2x](https://github.com/tdeekens/flopflip/assets/1877073/198c960d-5fb3-40f7-967d-4b16952ccb53)

Any naming in flopflip can be different and the list does not have to employ the same number.

We have some use cases in flopflip for this.

1. User comes to page, flag is cached.
1.1. Later fetch shows flag has the _same_ value in remote
1.2. Later fetch shows flag has _different_ value in remote
2. User comes to page, new flag is configured
3. User comes to page, flag is not cached
3.1. A default flag is configured
3.2. A default flag is not configured

The above list might not yet be complete but gives an idea for cases.

Currently the `cachePolicies` could be:

1. `stickyCache`

If a cached flag is found, it's not subscribed to. No network request. The cache won't update. A user is "stuck" with the cached flag value until the cache is pruned.

3. `cacheAndNetwork`

No matter if the flag is in the `cache`, a flag subscription is setup and the result is used. The cache will always be updated after the network request.

4. `cacheFirst`

The cache is used if a flag is found in it. A flag subscription is setup and the cache will be updated. The application however is not notified it the flag has a different values form the cache. Only a reload will make that change take effect.

**Comment by CarlosCortizasCT** [comment]
@tdeekens Thanks a lot for this proposal, it looks like a very nice feature for this library to have 💯 

I wanted to also share another point of view if that's ok.

I agree with the proposal to introduce a new attribute which allows users to enable a client-side cache and how to control it, however I'd like to suggest maybe a slightly narrower initial surface for the feature as well as some different naming.

From my point of view, I find it difficult to find a common use case for `stickyCache` as it will need some imperative implementation to clear/update the cached value. Perhaps you already how some use cases in mind. If so, could you share? 🙏 

My idea (at least) for a first implementation is that it will always be a network request (subscription) no matter if the cache is empty or not. The main difference is what we want to do when the remote value is resolved and is different than the cached one. But the process would be the same for a given flag:
1. Read the value from the defaults
2. (if cache is enabled) override the value from the cache
3. Yield the value
4. Resolve (asynchronously) remote value
5. (if cache is enabled) update cached value
6. Decide whether we update the flag runtime value

Given this process, the user has to make two decisions:
* Should the cache be enabled?
* Should the remote resolve value should be immediately applied?

In order to determine the setup the library would expose a new attribute named **cacheMode** with two values: **eager** and **lazy**:
- The existence of any value will indicate that consumer wants to enable the caching feature
- **eager** means the resolved remote value (besides updating the cache) will be reflected immediately in the UI
- **lazy** means the resolved remote will be updated in the cache but nothing else would happen

Here's a diagram where I try to depict this proposal:
![flopflip_cache drawio](https://github.com/tdeekens/flopflip/assets/97907068/c0b48b29-84e0-49b3-af12-006c188bae6a)

**Comment by tdeekens** [comment]
Hi @CarlosCortizasCT,

thanks for the feedback. I started looking at code and prototyping it a bit. I really like the simple naming and idea. I think I'll publish it under a breaking change as it also allows to remove a legacy configuration option.

Generally, we will have to values:

1. `cacheIdentifier`: to define if we want a localstorage or session storage based cache
    - This is quite deep in the library and works and I'd prefer not to remove
2. `cacheMode`: how we define `lazy` and `eager` caching behaviour

I'll share some early PR after the weekend to discuss things on code.

**Comment by tdeekens** [comment]
Another note before I forget: there are default flags (hard-coded) which are passed by consumers. Then there are cached flags and remote flags. 

```
Given a user passes default flags
And has cached flags different from default flags
And a remote flag similar to the default flag
```

There can be flickering. Not opting into default flags can be "risky" given not all user may have cached flags and the connection to LaunchDarkly is blocked (by e.g. an Ad Blocker) and you then opt into the `false` variation. 

An option is to use the helper from the adapter I've added 2-3 weeks ago

```js
import ldAdapter, { getCachedFlags } from '@flopflip/launchdarkly-adapter';
```

...as then you can `getCachedFlags('local')` and pass the return as default flags into the `adapterArgs`. This means you can have default flags (hard-coded) override them with cached flags. The advantage is rather internal but initial React "setState" of default flags will include cached flags. This is otherwise not possible or may need some thinking.

**Comment by tdeekens** [comment]
I have a rough idea in my head. Hopefully I have a quiet evening soon to code it up.

**Comment by tdeekens** [comment]
Made some decent progress on ideas in the draft PR #1888.

The main challenge left now is to move the cached flag state into React before the passed default flags of a consumer are flushed. This way we would avoid two passes. Right now we would have:

1. User passes default flags
2. A `setState` flushes them into state on React
3. The adapter used receives them as state and will do things (depends on adapter)
4. Adapter pull cached flags which causes a `setState` again

If 2. and 4. are batched or "close enough", then no flickering will occur.

We would however merge 4. into 2. by having the `@flopflip/react` component pull flags out of the cache before flushing default flags. This however, is a bit "tricky" as importing the cache module and the underlying session- or localstorage variant is an asynchronous import which can cause a delay.

Another option is also to not "hide" this from consumers but have them import the cache module and pass the result of `getCachedFlags` into flopflip - similar to noted above.

Lastly, there is the 🐘 in the room how we handle `reconfiguration`. If an application reconfigures the adapter (e.g. setting a project key value), then many users will expect that any change in flags to immediately take effect. In lazy mode it won't. The user however, could transition an entire adapter into eager mode by passing it on the adapterArgs.
