### ISSUE TITLE
[@flopflip/launchdarkly-adapter] Specify different key to trigger `reconfigure`

### ISSUE THREAD

**Issue by joshparolin** [tdeekens/flopflip#268]
Hey there - I'm not sure if I have a unique use case or not, but here goes:

**Issue:**
- We use a user's `email` as their `key` with LaunchDarkly
- We have some flags that we configure on a per user basis / user segments. However, we also have flags that are dependent on the custom context of what organizationId and eventId the user is currently viewing.
- This works great when forcing a new page load when the user jumps from event to event. However, when sticking with SPA routing, I can't figure out how to force the LaunchDarkly adapter to `reconfigure` because technically the user's key (`email`) is not changing.

**Solution I'm thinking of:**
- My thinking is to allow a different `key` to be provided to the adapter for it to check against instead of using `key`. For example, if I pass a prop of `reconfigureKey`, the adapter will use that for it's internal validation. If `reconfigureKey` is not provided, it falls back to `key`.

**Example solution:**
```
  if (adapterState.user && (adapterState.user.configureKey !== user.configureKey || adapterState.user.key !== user.key)) {
    adapterState.user = ensureUser(user);

    return changeUserContext(adapterState.user);
  }
```

Reference line: https://github.com/tdeekens/flopflip/blob/master/packages/launchdarkly-adapter/modules/adapter/adapter.js#L75

I wanted to make sure I'm not blind to any other provided solutions. If so, please enlighten me! 🤓  Otherwise, let me know if you'd be interested in this as a PR - else, I can fork.

Appreciate your hard work!

**Comment by tdeekens** [comment]
Thanks for opening the issue. Really appreciate the kind words!

I understand your use case and I also think that a the E-Mail being a `key` is a perfect use has. In that the an E-Mail address or any primary key e.g. from a database makes a perfect user key. 

The part I don't yet fully manage to follow is:

> LaunchDarkly adapter to reconfigure because technically the user's key (email) is not changing.

In that: why does the adapter need to reconfigure? I assume to `changeUserContext` from the client's side? So that any newly "acquired characteristics" are updated with LD?

Thinking about it a bit it feels a bit like we should `reconfigure` once the user data is not `deep-equal` to the previous? 

_Note_: the LD adapter exposes the `{ changeUserContext }` function which I don't recommend. I might also like the equality check a bit more right now rather than manual/imperative updating of the key.

**Comment by tdeekens** [comment]
What do you think about: https://github.com/tdeekens/flopflip/pull/270

**Comment by joshparolin** [comment]
@tdeekens - Great idea re: using `deep-equal`. That will solve the use case here. Thanks for the quick response and for taking care of the PR!

**Comment by tdeekens** [comment]
https://github.com/tdeekens/flopflip/releases/tag/%40flopflip%2Flaunchdarkly-adapter%402.2.1
